# Properties
title: Blogdan;
author: Bogdan Kyuchukov
email: bogdankyuchuk@gmail.com
twitter_username: BKyuchukov
github_username:  bkyuchuk
linkedin_username: bogdan-kyuchukov-9313a9188
permalink: /:categories/:title

# Build settings
remote_theme: bkyuchuk/custom-clean-blog-jekyll@main

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true